name: Deploy Frontend via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Build and Deploy Frontend to /frontend_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # sesuaikan jika kamu pakai versi lain

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload via FTPS
        uses: sebastianpopp/ftp-action@v1.3.3
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./dist
          remoteDir: /frontend_build
          protocol: ftps
